name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Get the number of tags (releases)
        id: get_version
        run: echo "::set-output name=release_count::$(git tag | wc -l)"

      - name: Get the number of commits
        id: get_commits
        run: echo "::set-output name=commit_count::$(git rev-list --count HEAD)"

      - name: Set version number
        id: set_version
        run: echo "::set-output name=version::0.${{ steps.get_version.outputs.release_count }}.${{ steps.get_commits.outputs.commit_count }}"

      - name: Update package.json with new version
        run: |
          npm version ${{ steps.set_version.outputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

      - name: Upload Windows build artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkedAuthenticator-${{ steps.set_version.outputs.version }}-windows
          path: build/SkedAuthenticator-${{ steps.set_version.outputs.version }}.exe
      
      - name: Upload macOS DMG
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkedAuthenticator-macos-dmg
          path: build/SkedAuthenticator-${{ steps.set_version.outputs.version }}-arm64.dmg

      - name: Upload Linux AppImage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkedAuthenticator-linux-AppImage
          path: build/SkedAuthenticator-${{ steps.set_version.outputs.version }}.AppImage
      
      - name: Upload Linux Snap Package
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: SkedAuthenticator-linux-snap
          path: build/authenticator_${{ steps.set_version.outputs.version }}_amd64.snap
